site_name: conrich
site_description: "conrich's documentation made with MkDocs."
repo_url: "https://github.com/concords6016/conrich_docs/"
copyright: "conrich is licensed under the <a href='https://github.com/concords6016/conrich_docs/blob/master/LICENSE'>MIT license</a>"
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Overview: index.md
  - Installation: install.md
  - User Guide:
    - Table of content: tutorial/user_guide.md
    - Login API: tutorial/login.md
    - Place Order: tutorial/place_order.md
    - Register Report: tutorial/register_report.md
    - Register Quote: tutorial/register_quote.md
  - FAQ: faq.md
shortcuts:
  help: 191    # ?
  next: 39     # right arrow
  previous: 37 # left arrow
  search: 83   # s
markdown_extensions:
  - admonition
plugins:
  - search
  - table-reader:
      data_path: "docs/sum_chart"